version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm init --yes
  build:
    commands:
      - npm install
      - npm run build
  artifacts:
    files:
      - README.md
      - app.js
      - package.json
      - package-lock.json
      - public/*
